### ISSUE TITLE
0x73696d616f - Calling `SNStInit` just 1 block after `SNstDeploy` will always revert and deposits will be stuck getting no yield

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-makerdao-endgame-judging#1]
0x73696d616f

Medium

# Calling `SNStInit` just 1 block after `SNstDeploy` will always revert and deposits will be stuck getting no yield

### Summary

Not calling `SNst::drip()` before `SNst::file()` in `SNstInit::init()` will DoS the protocol until a manual fix is applied. Depositing at the same block that `SNst` is deployed will get the funds stuck getting no yield until the manual fix comes through.

### Root Cause

[SNst::init()](https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/sdai/deploy/SNstInit.sol#L62-L64) does not call `SNst::drip()` before `SNst::file()`:
```solidity
function init(
    ...
) internal {
    ...
    dss.vat.rely(instance.sNst);
     //@audit note that SNst::drip() is not called, which reverts if block.timestamp != rho
    SNstLike(instance.sNst).file("nsr", cfg.nsr);
    ...
}
```
So it reverts on [SNst::file()](https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/sdai/src/SNst.sol#L206):
```solidity
function file(bytes32 what, uint256 data) external auth {
    ...
        require(rho == block.timestamp, "SNst/chi-not-up-to-date");
    ...
}
```
Additionally, deposits can be made when `block.timestamp == rho`, as `SNst::drip()` does [not](https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/sdai/src/SNst.sol#L226) call `vat::suck()`, which is what makes it revert as `vat::rely()` has not yet been set. After 1 block, they can not withdraw because `block.timestamp != rho` and `SNst::drip()` calls [vat::suck()](https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/sdai/src/SNst.sol#L221), which reverts.
```solidity
function drip() public returns (uint256 nChi) {
    ...
    if (block.timestamp > rho_) {
        ...
        vat.suck(address(vow), address(this), diff * RAY); //@audit reverts before vat::rely() is called in SNstInit
        ...
    } else { //@audit when block.timestamp == rho it goes here, allowing deposits
        nChi = chi_;
    }
    ...
}
```

### Internal pre-conditions

1. `SNstInit::init()` must not be called in the same block `SNstDeploy::deploy()` is called.

### External pre-conditions

None.

### Attack Path

1. `SNstDeploy::deploy()` deploys the token.
2. `$NST` is deposited into `SNst` in the same block of the deployment.
3. Unless `SNstInit::init()` is called in the same block as the previous 2 points, it will be impossible to withdraw and deposits will get no yield.

### Impact

Funds are stuck until a manual `Vat::rely()` call is made allowing `SNst::drip()` to be called which allows withdrawals. When this call happens some time in the future, yield will be lost because the `nsr` is initially set to `1`, so deposits will get no interest.

### PoC

Add the following test to `SNst-integration.t.sol`:
```solidity
function testStuckDeposit() public {
    SNstInstance memory inst = SNstDeploy.deploy(address(this), pauseProxy, address(nstJoin));
    token = SNst(inst.sNst);

    address user = makeAddr("user");
    vm.startPrank(user);
    deal(address(nst), user, 100 ether);
    nst.approve(address(token), type(uint256).max);
    token.deposit(100 ether, user);
    vm.stopPrank();

    skip(1);

    vm.startPrank(pauseProxy);
    vm.expectRevert("SNst/chi-not-up-to-date");
    token.file("nsr", 1000000001547125957863212448); // init lib would also revert
    vm.stopPrank();

    vm.startPrank(user);
    vm.expectRevert("Vat/not-authorized"); // drip() fails as rely() was not called
    token.redeem(100 ether, user, user);
}
```

### Mitigation

`SNst::init()` must call `SNst::drip()` before `SNst::file()`:
```solidity
function init(
    ...
) internal {
    ...
    dss.vat.rely(instance.sNst);
    
    SNstLike(instance.sNst).drip(); //@audit add this so SNst::file() does not revert

    SNstLike(instance.sNst).file("nsr", cfg.nsr);
    ...
}
```
Additionally, deposits must not be allowed at the block `SNst::deploy()` is called, or they will be stuck until `SNst::init()` is executed, which could take some time. The easiest fix is to set `rho` 1 block in the past, such that deposits will revert on `SNst::drip()` when calling `vat::suck()` before `vat::rely()` has been called in `SNst::init()`:
```solidity
function initialize() initializer external {
    ...
    rho = uint64(block.timestamp - 1); //@audit this stops deposits before SNst::init() is called
    ...
}
```

**Comment by 0xsimao** [comment]
Escalate

> Regarding the claim about DoS, the contract shouldn't be considered as for users usage until active via governance spell cast (which adds it in the chainlog). Users could also be depositing in contracts that are deployed and never used or any other random contract in the existance of the blockchain, they shouldn't do that.

This line of reasoning is flawed because users trust Maker, so if a contract is deployed and allows actions like depositing, users will assume it's safe and beneficial to interact with it, especially when motivated by potential yield. Users are incentivized to maximize returns and will seek to deposit as early as possible. Therefore, the contract should never allow deposits before it's fully configured and the governance spell is called, as doing so due to incomplete validation and faulty configuration leads to stuck funds.

The risk of users interacting with the incomplete `SNST` contract would only be mitigated if the issue was explicitly documented in the readme or codebase, clearly warning users not to deposit when the contract is deployed, or their funds might be stuck. Since no such warning was provided, users would be unaware of the risks, making the issue valid and a real risk.

The rules state the following:
> DoS issues where no funds would be locked or protocol functionality is blocked but one can still withdraw should be considered low severity at most.

This establishes a clear distinction between DoS issues that block withdrawals and those that don't. According to these guidelines, DoS issues where funds remain accessible and withdrawals are possible are deemed low severity at most. However, in this case, withdrawals are blocked until a manual fix is applied, which justifies classifying the issue as medium severity.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> > Regarding the claim about DoS, the contract shouldn't be considered as for users usage until active via governance spell cast (which adds it in the chainlog). Users could also be depositing in contracts that are deployed and never used or any other random contract in the existance of the blockchain, they shouldn't do that.
> 
> This line of reasoning is flawed because users trust Maker, so if a contract is deployed and allows actions like depositing, users will assume it's safe and beneficial to interact with it, especially when motivated by potential yield. Users are incentivized to maximize returns and will seek to deposit as early as possible. Therefore, the contract should never allow deposits before it's fully configured and the governance spell is called, as doing so due to incomplete validation and faulty configuration leads to stuck funds.
> 
> The risk of users interacting with the incomplete `SNST` contract would only be mitigated if the issue was explicitly documented in the readme or codebase, clearly warning users not to deposit when the contract is deployed, or their funds might be stuck. Since no such warning was provided, users would be unaware of the risks, making the issue valid and a real risk.
> 
> The rules state the following:
> > DoS issues where no funds would be locked or protocol functionality is blocked but one can still withdraw should be considered low severity at most.
> 
> This establishes a clear distinction between DoS issues that block withdrawals and those that don't. According to these guidelines, DoS issues where funds remain accessible and withdrawals are possible are deemed low severity at most. However, in this case, withdrawals are blocked until a manual fix is applied, which justifies classifying the issue as medium severity.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
To clarify this attack:
1. If the `SNStInit` is called in the same block as `SNStDeploy` the issue will not happen?
2. Deposit must be called in the block as deployment or it can be any block, but between the deployment and the call to `init`?

**Comment by 0xsimao** [comment]
1. That's correct, it only happens if init is not called in the same block as deploy.

2. Deposit must be called in the same block as deploy.

**Comment by bb22ff** [comment]
Impact is locked funds until a fix spell is executed, which is [at most 50 hours (gov reaction time)](https://github.com/makerdao/sherlock-contest/blob/9a01337e8f82acdf699a5c1c54233636c640ca89/README.md#severity-definitions). 

However, Sherlock rules require at least [7 days lock for a medium](https://docs.sherlock.xyz/audits/judging/judging#iii.-sherlocks-standards), so the issue cannot be a medium.

> The issue causes locking of funds for users for more than a week.

**Comment by sunbreak1211** [comment]
As was stated, a contract that hasn't been ratified by governance during the spell process is not considered part of the Maker protocol and depositing to it is a user mistake.

Note that in this case, even that is not possible since up until the spell casting NST is not in circulation, so no one can deposit it and there is no possible denial of service. This is because the NstJoin is not relied yet, so no one can mint NST (see NST init script - https://github.com/makerdao/nst/blob/dev/deploy/NstInit.sol#L54).

**Comment by WangSecurity** [comment]
Agree with the sponsor above. Maker's design is to ratify contracts via spell, so the users are not expected to deposit before them. In that case, I agree it's a mistake of the user to deposit into the contract when they shouldn't. Additionally, as said above, with the correct deployment this issue is not even possible. Hence, I believe it has to remain as it is, planning to reject the escalation.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xsimao](https://github.com/sherlock-audit/2024-06-makerdao-endgame-judging/issues/1/#issuecomment-2290020895): rejected
