### ISSUE TITLE
0xaliyah - h-01 reentrant with stolen of funds  0xaliyah

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-makerdao-endgame-judging#14]
0xaliyah

High

# h-01 reentrant with stolen of funds  0xaliyah

## Summary

1. while the temp. var; `balance` L222 is the misinformation toward the effect at L237
2. while the temp. var; `balance` L222 is the lagging indication toward the effect at L237 if the `from` address was made any withdrawal or any transferFrom in the way that induced that reentry
3. L222 is the lagging indication
4. the `from` address made a withdrawal when the `transferFrom` function gave up control to the attacker at L222
5. since withdraw made and L222 now stale then L237 give the now empty-balance `from` address free increment

## Vulnerability Detail

1. recipients for free balance increment may be found

## Impact

1. high impact + high likeliness owasp

## Code Snippet

[poc](https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/endgame-toolkit/src/SDAO.sol#L237)

## Tool used

Manual Review

## Recommendation

[checks effects interactions](https://fravoll.github.io/solidity-patterns/checks_effects_interactions.html)
[Will Shahda](https://medium.com/coinmonks/protect-your-solidity-smart-contracts-from-reentrancy-attacks-9972c3af7c21)

**Comment by telome** [comment]
Spam/bot submission?

**Comment by sabatha7** [comment]
@telome if your asking if the attacker will spam/brute force . I dont think it will be the most elegant approach by the attacker. I suspect they will plot everything offchain first.  but brute force bot is not unlikely since he just need to have a xl large balance and then transfer micro balance each time.

**Comment by sabatha7** [comment]
@telome @sunbreak1211 There might be multiple easier attack paths that we mustn't afford to miss as well, such as running the `transferFrom` function in quick succession. Consider this: If the maximum available balance is the original balance, then:

1. Run `transferFrom` with the maximum balance as an argument.
2. How many `transferFrom` calls can we successfully execute in quick succession to capture that maximum balance (Line 222) before the `from` address's balance is deducted to zero, causing a revert due to insufficient funds?

Essentially, the excess balance that could be exploited can be approximated by `(max(1, ((balance[to].latest - balance[to].original) / maximum))-1)*maximum`. sherlock discord @0xaliyah

**Comment by sabatha7** [comment]
@sunbreak1211 @telome 
```python
# Tn = 0: Initial state before the attack
OriginalBalance = 100000000
FraudBalance = 0

def transferFrom(addressFrom, addressTo, value):
    # Tn = 1: Capture balance before reentrant call
    ReentrantBalance = reentrantBalance(addressFrom)  # @Tn = 1
    
    # Tn = 3: Deduct the manipulated balance
    BalanceOf[addressFrom] = ReentrantBalance - value  # @Tn = 3 
    BalanceOf[addressTo] += value  # @Tn = 3

def reentrantBalance(addressFrom):
    # Tn = 2: Manipulate balances within reentrant call
    global FraudBalance
    FraudBalance = BalanceOf[addressFrom]
    BalanceOf[addressFrom] = 0  # @Tn = 2
    return FraudBalance  # @Tn = 1

# Tn = 4: Final state check
AddressFrom = 5
AddressTo = 6
BalanceOf = {AddressFrom: OriginalBalance, AddressTo: 0}

transferFrom(AddressFrom, AddressTo, 0.1)
assert(FraudBalance == OriginalBalance and BalanceOf[AddressFrom] == OriginalBalance - .1 and BalanceOf[AddressTo] == 0.1)
```
